name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
  pull_request:
    paths:
      - "packages/snfoundry/contracts/**"

jobs:
  snfoundry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v 2.5.4

      - name: Install snfoundryup
        run: curl -L https://raw.githubusercontent.com/foundry-rs/starknet-foundry/master/scripts/install.sh | sh

      - name: Install snforge
        run: snfoundryup -v 0.25.0

      - name: Run snforge tests
        run: snforge test
        working-directory: ./packages/snfoundry/contracts
